version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
    
    command: "npm run dev"

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
    
  

